### ISSUE TITLE
I don't have a crush

### ISSUE THREAD

**Issue by ghost** [pGeek64/ordinarysite#1]
Please fix

**Comment by pGeek64** [comment]
> Please fix

you have me 👉👈

**Comment by Morgan-le-Fay** [comment]
Todd says liberals are trying to cancel skyrim for racism against cat people, what will you do to ensure this timeless classic survives?

**Comment by pGeek64** [comment]
I ALREADY BOUGHT IT 3 TIMES AND DOWNLOADED IT ON GAMEPASS

**Comment by Morgan-le-Fay** [comment]
Inshallah issue fixed
